# Generated by Django 5.1.4 on 2025-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urna',
            name='contingencia',
            field=models.BooleanField(default=False),
        ),
    ]
