# Generated by Django 5.1.4 on 2025-01-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logis', '0003_distribuicao_urna_bio_distribuicao_urna_contingencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicao',
            name='target_zones',
            field=models.ManyToManyField(related_name='received_distribuicoes', to='Logis.zonaeleitoral'),
        ),
    ]
