# Generated by Django 5.1.4 on 2025-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logis', '0004_distribuicao_target_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuicao',
            name='target_zones',
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='target_zones',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
